server:
  port: 8080
  servlet:
    context-path: /welcome

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/order_eat"
    username: root

  jpa:
    hibernate:
      ddl_auto: update
    show-sql: true
