server:
  port: 90
  servlet:
    context-path: /welcome

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_eat
    username: root

  jpa:
    hibernate:
      ddl_auto: update
    show-sql: true

jwt:
  signerKey: "LTuWc5TrsQmXblYD/myLnSvlv5MuXnCJCtbkK2mCjmPk5tDyyDKWOnLmmGMuPvws"